id: P8BE74A08
initial_creation_type: ocr
source_metadata:
  volumes:
    7645e090c0244b9193a1572ffaae9fb9:
      base_file: v083.txt
      image_group_id: I1PD95928
      title: བསྟན་བཅོས་ཚིགས་སུ་བཅད་པ་བསྡུས་པ།
      total_pages: 1296
      volume_number: 83
